### ISSUE TITLE
question: why is there no server:sendToClient?

### ISSUE THREAD

**Issue by RokonShimo** [camchenry/sock.lua#14]
Basically the direct opposite of `server:sendToAllBut`. Right now, I'm having to do a clunky workaround with client:getIndex and server:sendToPeer.

**Comment by RokonShimo** [comment]
I was thinking of `client:send()`

**Comment by Ismoh** [comment]
This might help in future:
[server:sendToPeer()](https://github.com/camchenry/sock.lua/blob/4c9fd32f0f33eef8da881206e8f1d5f930b99746/sock.lua#L349-L364)
