### ISSUE TITLE
sock.lua: 724: Error during service

### ISSUE THREAD

**Issue by leankyr** [camchenry/sock.lua#16]
Hey camchenry,

Do you or anyone know what the error above stands for? the library was kinda working and it is suddenly throwing this at me. I am trying to get better at networking. 

Cheers.

**Comment by Ismoh** [comment]
How do you fixed that?

**Comment by leankyr** [comment]
I just port-forwarded my router correctly and I stopped having this issue as I can recall

**Comment by Ismoh** [comment]
Thanks4reply!
